//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarService_SteeringWheel.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.OrderProduct = new HashSet<OrderProduct>();
        }
    
        public string ProductArticleNumber { get; set; }
        public string ProductName { get; set; }
        public string ProductDescription { get; set; }
        public string ProductCategory { get; set; }
        public string ProductImage { get; set; }
        public string ProductManufacturer { get; set; }
        public decimal ProductCost { get; set; }
        public Nullable<byte> ProductDiscountAmount { get; set; }
        public int ProductQuantityInStock { get; set; }
        public string ProductStatus { get; set; }
        public string Unit { get; set; }
        public byte MaxDiscountAmount { get; set; }
        public string Supplier { get; set; }
        public Nullable<int> CountInPack { get; set; }
        public Nullable<int> MinCount { get; set; }
    
        public virtual ICollection<OrderProduct> OrderProduct { get; set; }

        public String Background
        {
            get
            {
                if (this.ProductDiscountAmount >= 15)
                {
                    return "#7fff00";
                }
                return "#fff";
            }
        }

        public String CostWithDiscount
        {
            get
            {
                if (this.ProductDiscountAmount > 0)
                {
                    Double cwd =
                        Math.Round(
                            Convert.ToDouble(this.ProductCost) *
                            (
                             1 -
                             Convert.ToDouble(this.ProductDiscountAmount)
                             / 100
                            )
                            , 2
                        );
                    return cwd.ToString();
                    // return "Curwa";
                }

                return this.ProductCost.ToString();
            }
        }

        public String JustCost
        {
            get
            {
                return Math.Round(this.ProductCost, 2).ToString();
            }
        }

        public String ImgPath
        {
            get
            {
                if (this.ProductImage.Length > 0)
                {
                    String path = "/Resources/" + this.ProductImage;

                    return path;
                }

                return "/Resources/picture.png";
            }
        }
    }
}
